# .github/workflows/format-check.yml
name: Format check
on: [push, pull_request]
jobs:
  cljfmt:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '21' }
      - run: brew install clojure-lsp/brew/clojure-lsp-native
      - run: clojure-lsp clean-ns --dry
      - run: clojure-lsp format --dry
